https://scikit-learn.org/stable/modules/multiclass.html

1. multiclass classification

In [1]:
import numpy as np 
# 1d vector contain more than 2 discrete values
y = np.array(['apple','pear','apple'])
print(y)

['apple' 'pear' 'apple']


In [2]:
from scipy import sparse
row_ind = np.array([0,1,2])
col_ind = np.array([1,2,1])
y_sparse = sparse.csr_matrix((np.ones(3),(row_ind,col_ind)))
print(y_sparse)

  (0, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0


2. multi-label classification


In [5]:
# 1d 
y = np.array([[1,0,0,1],[0,0,1,1],[0,0,0,0]])
print(y)
# same y in sparse matrix form
y_sparse = sparse.csr_matrix(y)
print(y_sparse)

[[1 0 0 1]
 [0 0 1 1]
 [0 0 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	1
  (1, 3)	1
